"""
main.py - Challenge 4: Stateful Multi-Agent Workflow Orchestration & HITL Approvals
Orchestrates the ManuscriptShield AI audit pipeline over Microsoft Foundry's stateful Responses API (/openai/v1/).
Handles Human-in-the-Loop (HITL) MCP tool approval events seamlessly.
"""

import os
import sys
import json
import time
import argparse
import re
from pathlib import Path
from dotenv import load_dotenv
from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient
from openai.types.responses.response_input_param import McpApprovalResponse, FunctionCallOutput

# Ensure tracing environment variable is set before SDK imports
os.environ["AZURE_EXPERIMENTAL_ENABLE_GENAI_TRACING"] = "true"

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../2_build")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../3_monitor")))

from tools import check_thresholds
from tracing_setup import setup_tracing


def print_agent_comment(agent_name, purpose, response_text, limit=900):
    """Print a labeled, readable excerpt from an agent response for the demo."""
    comment = (response_text or "No response text returned.").strip()
    print(f"\n   [{agent_name}] {purpose}")
    print("   Comment:")
    for line in comment[:limit].splitlines():
        print(f"      {line}")
    if len(comment) > limit:
        print("      ... [comment shortened for terminal display]")


def extract_score(response_text):
    match = re.search(r"(?:SCORE|TRUST_INDEX)\s*:\s*(\d{1,3})", response_text or "", re.IGNORECASE)
    return match.group(1) if match else "Not reported"


def find_demo_problem_notes(manuscript_text):
    notes = []
    if re.search(r"[\w.+-]+@[\w.-]+\.[A-Za-z]+", manuscript_text):
        notes.append(("PII exposure", "Author contact information is present and must be removed for double-blind review."))
    if re.search(r"IRB\s*(?:approval\s*)?(?:code|number)?\s*:\s*(?:NONE|N/A|missing)", manuscript_text, re.IGNORECASE):
        notes.append(("Missing ethics approval", "Human-subject research without a verifiable IRB approval code is a publication blocker."))
    if re.search(r"fake|9999|invalid", manuscript_text, re.IGNORECASE) and re.search(r"DOI|doi", manuscript_text):
        notes.append(("Suspicious citation", "A fake or invalid DOI cannot support the manuscript's claims and must be verified or removed."))
    if re.search(r"fake-user|example\.com", manuscript_text, re.IGNORECASE):
        notes.append(("Unverified dataset source", "A placeholder repository or license cannot establish reproducibility or legal reuse rights."))
    if "99.4%" in manuscript_text and "Measured N" in manuscript_text:
        notes.append(("High accuracy claim", "The reported accuracy needs to reconcile with the table counts and evaluation method before publication."))
    return notes


def write_review_report(
    manuscript_path,
    manuscript_text,
    clean_manuscript,
    audit_results,
    trust_score,
    threshold_result,
    final_editorial_text,
    mcp_enabled,
):
    report_directory = Path(manuscript_path).parent / "reports" if manuscript_path else Path("reports")
    report_directory.mkdir(exist_ok=True)
    source_name = Path(manuscript_path).stem if manuscript_path else "sample_manuscript"
    report_path = report_directory / f"{source_name}_review_report.md"
    problem_notes = find_demo_problem_notes(manuscript_text)
    threshold_text = threshold_result or "Not returned"
    trust_text = str(trust_score) if trust_score is not None else "Not reported"

    lines = [
        f"# ManuscriptShield Review Report: {source_name}",
        "",
        "> Generated by the ManuscriptShield multi-agent proof of concept.",
        "",
        "## Executive Summary",
        "",
        f"- Overall Trust Index: **{trust_text}/100**",
        f"- Editorial MCP: **{'Enabled' if mcp_enabled else 'Disabled'}**",
        f"- Threshold gate: `{threshold_text}`",
        f"- Detected review issues: **{len(problem_notes)}**",
        "",
        "## Manuscript Profile",
        "",
        f"- Source file: `{manuscript_path or 'built-in sample'}`",
        f"- Characters: {len(manuscript_text)}",
        f"- Words: {len(manuscript_text.split())}",
        "",
        "## Content Before Review",
        "",
        "```text",
        manuscript_text[:1800].strip(),
        "```",
        "",
        "## Anonymization Result",
        "",
        "The anonymizer removed or masked identifying content before the specialist audits:",
        "",
        "```text",
        clean_manuscript[:1800].strip(),
        "```",
        "",
        "## Problems And Why They Matter",
        "",
    ]
    if problem_notes:
        for problem, reason in problem_notes:
            lines.append(f"### {problem}")
            lines.append("")
            lines.append(f"- **Why it is a problem:** {reason}")
            lines.append("")
    else:
        lines.extend(["No deterministic demo risk signals were detected.", ""])

    lines.extend(["## Agent Scores And Comments", "", "| Agent | Score | Meaning |", "| --- | ---: | --- |"])
    meanings = {
        "plagiarism": "100 = original / low similarity risk",
        "citation": "100 = citation integrity",
        "equations": "100 = mathematically sound",
        "contradiction": "100 = internally consistent data",
        "dataset": "100 = reproducible and licensed",
        "ethics": "100 = ethics compliance",
    }
    for role, result in audit_results.items():
        score = extract_score(result["text"])
        lines.append(f"| {result['name']} | {score} | {meanings.get(role, 'Higher is better')} |")
    lines.append("")
    for result in audit_results.values():
        lines.extend([f"### {result['name']}", "", result["text"].strip() or "No response text returned.", ""])

    lines.extend([
        "## Editorial Decision",
        "",
        final_editorial_text.strip() or "The synthesis response was represented by the threshold gate above.",
        "",
        "## Demo Note",
        "",
        "Scores and comments are generated by the configured Foundry agents. External services such as CrossRef, Turnitin, and a production editorial board are not connected in this proof of concept.",
        "",
    ])
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def load_existing_agents(project_client):
    """Load the latest version of each agent created by the build step."""
    agent_names = {
        "anonymizer": "Manuscript-A1-Anonymizer",
        "plagiarism": "Manuscript-A2-PlagiarismCheck",
        "citation": "Manuscript-A3-CitationAuditor",
        "equations": "Manuscript-A4-EquationsAgent",
        "contradiction": "Manuscript-A5-ContradictionDetector",
        "dataset": "Manuscript-A6-DatasetAuditor",
        "ethics": "Manuscript-A7-EthicsLegalAuditor",
        "synthesis": "Manuscript-A8-Synthesis",
    }
    agents = {}
    for role, agent_name in agent_names.items():
        versions = project_client.agents.list_versions(agent_name, limit=1, order="desc")
        agent = next(iter(versions), None)
        if agent is None:
            raise RuntimeError(
                f"No built version found for {agent_name}. Run .\\.venv\\Scripts\\python.exe .\\2_Build\\agents.py first."
            )
        agents[role] = agent
    return agents


def run_manuscript_review_pipeline(manuscript_path=None):
    """Executes end-to-end multi-agent review pipeline with HITL approval loop."""
    load_dotenv(override=True)

    endpoint = os.environ.get("FOUNDRY_PROJECT_ENDPOINT")
    model_name = os.environ.get("FOUNDRY_MODEL_NAME", "gpt-5.6-sol")
    mini_model = os.environ.get("FOUNDRY_MINI_MODEL", "gpt-5.6-sol")
    mcp_url = os.environ.get("EDITORIAL_MCP_URL")

    if not endpoint or "your-project" in endpoint:
        print("❌ ERROR: FOUNDRY_PROJECT_ENDPOINT is not properly configured in .env.")
        sys.exit(1)

    # Initialize OpenTelemetry Tracing to Azure Monitor
    tracer = setup_tracing()

    print("\n=== ManuscriptShield AI: Stateful Workflow Execution ===")
    print(f"Connecting to Microsoft Foundry Project: {endpoint}")

    credential = DefaultAzureCredential()
    with AIProjectClient(endpoint=endpoint, credential=credential) as project_client:
        openai_client = project_client.get_openai_client()

        # Step 1: Load Specialized Sub-Agents created by the build step
        print("\n1. Loading Existing Specialized Audit Sub-Agents...")
        agents = load_existing_agents(project_client)
        print(f"   Editorial MCP: {'enabled' if mcp_url else 'disabled'}")
        for role, agent_obj in agents.items():
            print(f"   ✓ Registered Agent [{role}]: {agent_obj.name} (Version: {agent_obj.version})")

        # Step 2: Initialize Stateful Conversation Session
        conversation = openai_client.conversations.create()
        print(f"\n2. Created Stateful Conversation Thread (ID: {conversation.id})")

        sample_raw_manuscript = """
        MANUSCRIPT TITLE: Quantum Machine Learning for Drug Discovery
        AUTHORS: Dr. Alice Smith (alice.smith@university.edu), Dr. Bob Jones
        GRANT ID: NIH-R01-CA998877

        ABSTRACT:
        We report 99.4% prediction accuracy for binding affinity.

        METHODS & ETHICS:
        Human subject data collected in 2024. IRB APPROVAL CODE: NONE (Exempt).
        Data repository: https://github.com/fake-user/drug-discovery-data (CC-BY License).

        REFERENCES:
        Smith et al., 2023. DOI: 10.1000/fake-doi-182.

        TABLE 1: BINDING AFFINITY RESULTS
        | Compound | Measured N | Reported Mean | p-value |
        | Cmp-A    | 25         | 84.1%         | 0.14    |
        | Cmp-B    | 30         | 72.3%         | 0.08    |
        """
        if manuscript_path:
            sample_raw_manuscript = Path(manuscript_path).read_text(encoding="utf-8")
            print(f"   ✓ Loaded manuscript file: {manuscript_path}")

        risk_signals = []
        if re.search(r"[\w.+-]+@[\w.-]+\.[A-Za-z]+", sample_raw_manuscript):
            risk_signals.append("author email / PII")
        if re.search(r"IRB|human subject|consent", sample_raw_manuscript, re.IGNORECASE):
            risk_signals.append("human-subject ethics statement")
        if re.search(r"DOI|10\.\d{4,9}/", sample_raw_manuscript, re.IGNORECASE):
            risk_signals.append("citation or DOI")
        if "|" in sample_raw_manuscript:
            risk_signals.append("table data")
        print("\n   Manuscript profile:")
        print(f"      Characters: {len(sample_raw_manuscript)}")
        print(f"      Words: {len(sample_raw_manuscript.split())}")
        print(f"      Review signals: {', '.join(risk_signals) or 'none detected'}")
        audit_results = {}
        trust_score = None
        threshold_result = None
        final_editorial_text = ""

        with tracer.start_as_current_span("manuscript_review_pipeline_run") as span:
            span.set_attribute("manuscript.id", "MS-2026-0921-QUANTUM")

            # Step 3: Anonymization (Pass 1)
            print("\n3. Executing Pass 1: Anonymizer Agent (PII & Metadata Scrubbing)...")
            res_anon = openai_client.responses.create(
                conversation=conversation.id,
                input=f"Anonymize this manuscript text for double-blind review: {sample_raw_manuscript}",
                extra_body={"agent_reference": {"name": agents["anonymizer"].name, "type": "agent_reference"}},
            )
            clean_manuscript = res_anon.output_text
            print_agent_comment(
                "Anonymizer",
                "Removed author identity, affiliation, grant, and metadata before review.",
                clean_manuscript,
                limit=500,
            )

            # Step 4: Specialist Sub-Agent Audits (Pass 2)
            print("\n4. Executing Pass 2: Plagiarism & AI Similarity Auditor...")
            plagiarism_res = openai_client.responses.create(
                conversation=conversation.id,
                input="Assess plagiarism and AI-paraphrasing risk in this clean manuscript. Return SCORE: 0-100 and explain the evidence: " + clean_manuscript,
                extra_body={"agent_reference": {"name": agents["plagiarism"].name, "type": "agent_reference"}},
            )
            audit_results["plagiarism"] = {
                "name": "Plagiarism / AI Similarity Auditor",
                "text": plagiarism_res.output_text,
            }
            print_agent_comment(
                "Plagiarism Auditor",
                "Estimated originality and AI-paraphrasing risk from writing patterns.",
                plagiarism_res.output_text,
            )

            print("\n   Executing Pass 2: Equations & Math Auditor...")
            equations_res = openai_client.responses.create(
                conversation=conversation.id,
                input="Check equations, numerical claims, and dimensional consistency. Return SCORE: 0-100 and explain the evidence.",
                extra_body={"agent_reference": {"name": agents["equations"].name, "type": "agent_reference"}},
            )
            audit_results["equations"] = {
                "name": "Equations & Math Auditor",
                "text": equations_res.output_text,
            }
            print_agent_comment(
                "Equations Auditor",
                "Checked mathematical claims and numerical consistency.",
                equations_res.output_text,
            )

            print("\n   Executing Pass 2: Citation Auditor...")
            citation_res = openai_client.responses.create(
                conversation=conversation.id,
                input=f"Audit all inline DOIs and references in this clean text: {clean_manuscript}",
                extra_body={"agent_reference": {"name": agents["citation"].name, "type": "agent_reference"}},
            )
            audit_results["citation"] = {
                "name": "Citation Integrity Auditor",
                "text": citation_res.output_text,
            }
            print_agent_comment(
                "Citation Auditor",
                "Checked DOI validity, references, and claim-to-source consistency.",
                citation_res.output_text,
            )

            print("\n   Executing Pass 2: Statistical & Table Contradiction Auditor...")
            contradiction_res = openai_client.responses.create(
                conversation=conversation.id,
                input="Parse Table 1 and verify N-counts, p-values, and 99.4% accuracy claim.",
                extra_body={"agent_reference": {"name": agents["contradiction"].name, "type": "agent_reference"}},
            )
            audit_results["contradiction"] = {
                "name": "Statistical Contradiction Detector",
                "text": contradiction_res.output_text,
            }
            print_agent_comment(
                "Contradiction Detector",
                "Compared table values, sample counts, p-values, and reported accuracy.",
                contradiction_res.output_text,
            )

            print("\n   Executing Pass 2: Dataset & License Auditor...")
            dataset_res = openai_client.responses.create(
                conversation=conversation.id,
                input="Check dataset links, licenses, reproducibility, and possible PHI/PII leakage. Return SCORE: 0-100 and explain the evidence.",
                extra_body={"agent_reference": {"name": agents["dataset"].name, "type": "agent_reference"}},
            )
            audit_results["dataset"] = {
                "name": "Dataset & License Auditor",
                "text": dataset_res.output_text,
            }
            print_agent_comment(
                "Dataset Auditor",
                "Checked data provenance, license claims, reproducibility, and data leakage.",
                dataset_res.output_text,
            )

            print("\n   Executing Pass 2: Ethics & Bioethics Auditor...")
            ethics_res = openai_client.responses.create(
                conversation=conversation.id,
                input="Verify IRB approval statement and human subject consent validity.",
                extra_body={"agent_reference": {"name": agents["ethics"].name, "type": "agent_reference"}},
            )
            audit_results["ethics"] = {
                "name": "Ethics & Legal Auditor",
                "text": ethics_res.output_text,
            }
            print_agent_comment(
                "Ethics Auditor",
                "Checked IRB approval, consent language, and human-subject risk.",
                ethics_res.output_text,
            )

            # Step 5: Editorial Synthesis & HITL Check (Pass 3)
            print("\n5. Executing Pass 3: Lead Editorial Synthesis Agent...")
            synthesis_res = openai_client.responses.create(
                conversation=conversation.id,
                input="Aggregate all sub-agent findings, compute Trust Index Score, execute check_thresholds, and issue Reviewer Packet.",
                extra_body={"agent_reference": {"name": agents["synthesis"].name, "type": "agent_reference"}},
            )

            # Step 6: Handle Function Calling & MCP Human Approval Loop
            print("\n6. Inspecting Response Outputs for Tools & Approvals...")
            for item in synthesis_res.output:
                item_type = getattr(item, "type", None)

                # Handle local function call (check_thresholds)
                if item_type == "function_call" and item.name == "check_thresholds":
                    print(f"   ⚙️ Executing local FunctionTool [{item.name}]...")
                    args = json.loads(item.arguments)
                    trust_score = args.get("trust_score", 72.0)
                    tool_result = check_thresholds(trust_score=trust_score)
                    threshold_result = tool_result
                    print(f"   ✓ Threshold result: {tool_result}")

                    synthesis_res = openai_client.responses.create(
                        model=model_name,
                        input=[
                            FunctionCallOutput(
                                type="function_call_output",
                                call_id=item.call_id,
                                output=tool_result,
                            )
                        ],
                        previous_response_id=synthesis_res.id,
                    )
                    print_agent_comment(
                        "Lead Synthesis",
                        "Aggregated audit comments and produced the publication recommendation.",
                        synthesis_res.output_text,
                        limit=1200,
                    )
                    final_editorial_text = synthesis_res.output_text

                # Handle MCP Tool Approval Request (Human-in-the-Loop Pause)
                elif item_type == "mcp_approval_request":
                    print(f"\n   🚨 [HUMAN EDITORIAL REVIEW REQUIRED]")
                    print(f"      Approval Request ID : {item.id}")
                    print(f"      Target MCP Server   : {item.server_label}")
                    print(f"      Tool Name           : {item.name}")
                    print(f"      Arguments           : {item.arguments}")

                    # Simulate Human Editor inspecting Reviewer Packet & approving manuscript with required revisions
                    print("\n   👤 Editor Decision: Approving manuscript subject to mandatory revision of IRB statements...")
                    approval_input = McpApprovalResponse(
                        type="mcp_approval_response",
                        approve=True,
                        approval_request_id=item.id,
                    )

                    # Resume workflow execution with editor's decision
                    final_res = openai_client.responses.create(
                        model=model_name,
                        input=[approval_input],
                        previous_response_id=synthesis_res.id,
                    )

                    print("\n=== Final Approved Editorial Decision ===")
                    print(final_res.output_text)
                    final_editorial_text = final_res.output_text

        report_path = write_review_report(
            manuscript_path,
            sample_raw_manuscript,
            clean_manuscript,
            audit_results,
            trust_score,
            threshold_result,
            final_editorial_text,
            bool(mcp_url),
        )
        print(f"\n8. Written review report: {report_path}")

        # Step 7: Cleanup only the conversation; built agent versions are reusable.
        print("\n9. Cleaning up conversation session; retaining built agent versions...")
        openai_client.conversations.delete(conversation.id)

        print("✅ Workflow Execution & Cleanup Complete!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the ManuscriptShield review workflow.")
    parser.add_argument(
        "--manuscript",
        help="Path to a UTF-8 text or Markdown manuscript file. Uses the built-in demo manuscript when omitted.",
    )
    args = parser.parse_args()
    run_manuscript_review_pipeline(args.manuscript)
